package com.example.login;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class AstronomerController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private AstronomerRepository astronomerRepository;

    @GetMapping("/addastronomer") // Map ONLY POST Requests
    public @ResponseBody
    String addNewAstronomer (@RequestParam String fname
            , @RequestParam String mname
            , @RequestParam String lname
            , @RequestParam String org
            , @RequestParam String username
            , @RequestParam String pw) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Astronomer a = new Astronomer();
        a.setFirstname(fname);
        a.setMiddlename(mname);
        a.setLastName(lname);
        a.setOrganization(org);
        a.setUsername(username);
        a.setPassword(pw);
        astronomerRepository.save(a);
        return "Saved";
    }
}
