package com.example.login;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
public class AuthController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private AstronomerRepository astronomerRepository;
    @Autowired
    private ScienceObserverRepository scienceObserverRepository;

    @PostMapping(value="/login", produces = MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public @ResponseBody
    String Login (@ModelAttribute Auth loginInfo) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Iterable<ScienceObserver> scienceObserver = scienceObserverRepository.findAll();
        Iterable<Astronomer> astronomer = astronomerRepository.findAll();
        for (Astronomer a:astronomer) {
            if(a.getUsername().equals(loginInfo.getUsername())) {
                if(a.getPassword().equals(loginInfo.getPassword())) {
                    return "Login Successfully";
                }
                return "Password Incorrect";
            }
        }
        for (User s:scienceObserver) {
            if(s.getUsername().equals(loginInfo.getUsername())) {
                if(s.getPassword().equals(loginInfo.getPassword())) {
                    return "Login Successfully";
                }
                return "Password Incorrect";
            }
        }
        return "Login Fail!!";
    }
}
