package com.example.login;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class ScienceObserverController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private ScienceObserverRepository scienceObserverRepository;

    @GetMapping("/addscienceobs") // Map ONLY POST Requests
    public @ResponseBody
    String addNewAstronomer (@RequestParam String fname
            , @RequestParam String mname
            , @RequestParam String lname
            , @RequestParam String cert
            , @RequestParam String username
            , @RequestParam String pw) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        ScienceObserver s = new ScienceObserver();
        s.setFirstname(fname);
        s.setMiddlename(mname);
        s.setLastName(lname);
        s.setCertificate(cert);
        s.setUsername(username);
        s.setPassword(pw);
        scienceObserverRepository.save(s);
        return "Saved";
    }
}
